<script setup lang="ts">
import { ref,reactive,computed,onMounted } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ArrowLeft,Save } from 'lucide-vue-next'
import { api,json } from '../../api/client'
import { useAuth } from '../../stores/auth'
import { dateInput } from '../../utils/formatDate'
import { formatNaira,toKobo } from '../../utils/formatNaira'
import type { Client,Invoice,Item,Page } from '../../types'
import LineItemsEditor from '../../components/LineItemsEditor.vue'
const auth=useAuth(),route=useRoute(),router=useRouter(),id=route.params.id,clients=ref<Client[]>([]),error=ref(''),busy=ref(false),loading=ref(true),discount=ref(0)
const form=reactive({client_id:'' as string|number,issue_date:dateInput(),due_date:dateInput(14),tax_percent:auth.user?.business.default_tax_percent||0,notes:'Thank you for your business.',terms:'Payment is due by the date shown.',items:[{description:'',quantity:1,unit_price_kobo:0}] as Item[]})
const subtotal=computed(()=>form.items.reduce((s,i)=>s+Math.round(i.quantity*i.unit_price_kobo),0)),tax=computed(()=>Math.round(Math.max(0,subtotal.value-toKobo(discount.value))*form.tax_percent/100))
onMounted(async()=>{try{
 let page=1,last=1;do{const result=await api<Page<Client>>('/clients?per_page=100&page='+page);clients.value.push(...result.data);last=result.last_page;page++}while(page<=last)
 if(id){const invoice=await api<Invoice>('/invoices/'+id);Object.assign(form,{client_id:invoice.client_id,issue_date:invoice.issue_date,due_date:invoice.due_date,tax_percent:invoice.tax_percent,notes:invoice.notes,terms:invoice.terms,items:invoice.items.map(i=>({description:i.description,quantity:i.quantity,unit_price_kobo:i.unit_price_kobo}))});discount.value=invoice.discount_kobo/100}
}catch(e){error.value=(e as Error).message}finally{loading.value=false}})
async function save(){busy.value=true;error.value='';try{const invoice=await api<Invoice>('/invoices'+(id?'/'+id:''),json(id?'PUT':'POST',{...form,discount_kobo:toKobo(discount.value)}));router.push('/invoices/'+invoice.id)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><RouterLink to="/invoices" class="back-link"><ArrowLeft :size="16"/>Back to invoices</RouterLink><div class="page-heading"><div><span class="eyebrow">MAKE YOUR WORK OFFICIAL</span><h1>{{ id?'Edit invoice':'Create invoice' }}<span class="heading-dot">.</span></h1><p class="muted">A few details now. A professional impression later.</p></div></div><p v-if="loading" class="loading">Loading invoice editor…</p><form v-else @submit.prevent="save"><div class="editor-grid"><div><section class="panel form-panel"><h2>The essentials</h2><label>Bill to<select v-model="form.client_id" required><option value="" disabled>Select a client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ client.name }}{{ client.company?' · '+client.company:'' }}</option></select></label><RouterLink to="/clients/new" class="text-link">+ Add a new client</RouterLink><div class="form-grid spaced"><label>Issue date<input v-model="form.issue_date" type="date" required></label><label>Due date<input v-model="form.due_date" type="date" :min="form.issue_date" required></label></div></section><section class="panel form-panel spaced"><h2>What’s on the invoice?</h2><LineItemsEditor v-model="form.items"/></section><section class="panel form-panel spaced"><h2>A personal touch</h2><label>Notes<textarea v-model="form.notes" rows="3"/></label><label>Terms<textarea v-model="form.terms" rows="2"/></label></section></div><aside><section class="panel form-panel summary"><span class="eyebrow">INVOICE SUMMARY</span><h2>The numbers</h2><label>Discount (₦)<input v-model.number="discount" type="number" min="0" :max="subtotal/100" step=".01"></label><label>Tax (%)<input v-model.number="form.tax_percent" type="number" min="0" max="100" step=".01" required></label><div class="total-row"><span>Subtotal</span><strong>{{ formatNaira(subtotal) }}</strong></div><div class="total-row"><span>Discount</span><span>− {{ formatNaira(toKobo(discount)) }}</span></div><div class="total-row"><span>Tax</span><span>{{ formatNaira(tax) }}</span></div><div class="total-row grand-total"><span>Total</span><strong>{{ formatNaira(subtotal-toKobo(discount)+tax) }}</strong></div><p class="muted">Saved as a draft. Review and send when you’re ready.</p><button class="button primary wide" :disabled="busy||!clients.length"><Save :size="16"/>{{ busy?'Saving…':'Save invoice' }}</button><RouterLink to="/invoices" class="button ghost wide">Cancel</RouterLink></section></aside></div><p v-if="error" class="error" role="alert">{{ error }}</p></form></template>