<script setup lang="ts">
import { ref,onMounted } from 'vue'
import { Plus,ArrowUpRight,ArrowLeft,ArrowRight,Search } from 'lucide-vue-next'
import { useInvoices } from '../../stores/invoices'
import { formatNaira } from '../../utils/formatNaira'
import { formatDate } from '../../utils/formatDate'
import StatusBadge from '../../components/StatusBadge.vue'
const store=useInvoices(),status=ref(''),search=ref(''),page=ref(1),error=ref(''),loading=ref(false),from=ref(''),to=ref('')
async function load(reset=false){if(reset)page.value=1;loading.value=true;try{await store.load('?'+new URLSearchParams({status:status.value,search:search.value,from:from.value,to:to.value,page:String(page.value)}))}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
onMounted(()=>load())
</script>
<template><div class="page-heading"><div><span class="eyebrow">FROM YOUR WORK TO YOUR WORTH</span><h1>Invoices<span class="heading-dot">.</span></h1><p class="muted">Every invoice. Every payment. A clearer picture.</p></div><RouterLink to="/invoices/new" class="button primary"><Plus :size="18"/>Create invoice</RouterLink></div><section class="panel"><div class="filter-row"><div class="tabs"><button v-for="s in ['', 'draft','sent','paid','overdue']" :key="s" :class="{active:status===s}" @click="status=s;load(true)">{{ s||'All invoices' }}</button></div><select v-model="status" @change="load(true)" aria-label="Filter status"><option value="">All statuses</option><option value="draft">Draft</option><option value="sent">Sent</option><option value="partially_paid">Partially paid</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="void">Void</option></select></div><form class="filter-controls" @submit.prevent="load(true)"><div class="search-input"><Search :size="16"/><input v-model="search" placeholder="Invoice number" aria-label="Search invoice number"></div><label>From<input v-model="from" type="date"></label><label>To<input v-model="to" type="date"></label><button class="button secondary small">Apply filters</button></form><p v-if="error" class="error">{{ error }}</p><div v-if="loading" class="loading">Loading invoices…</div><div v-else class="table-wrap"><table><thead><tr><th>Invoice</th><th>Client</th><th>Due date</th><th>Total</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="invoice in store.page?.data" :key="invoice.id"><td><RouterLink :to="'/invoices/'+invoice.id" class="table-main">{{ invoice.number }}</RouterLink><small>{{ formatDate(invoice.issue_date) }}</small></td><td><strong>{{ invoice.client.name }}</strong><small>{{ invoice.client.company }}</small></td><td>{{ formatDate(invoice.due_date) }}</td><td class="money">{{ formatNaira(invoice.total_kobo) }}</td><td class="money">{{ formatNaira(invoice.balance_kobo) }}</td><td><StatusBadge :status="invoice.status"/></td><td><RouterLink :to="'/invoices/'+invoice.id" class="icon-button" aria-label="Open invoice"><ArrowUpRight :size="18"/></RouterLink></td></tr><tr v-if="!store.page?.data.length"><td colspan="7" class="empty">No invoices match these filters. Create an invoice to get started.</td></tr></tbody></table></div><div v-if="store.page" class="pagination"><span>{{ store.page.total }} invoices · Page {{ page }} of {{ store.page.last_page }}</span><div class="actions"><button class="button secondary small" :disabled="page===1" @click="page--;load()"><ArrowLeft :size="15"/>Previous</button><button class="button secondary small" :disabled="page>=store.page.last_page" @click="page++;load()">Next<ArrowRight :size="15"/></button></div></div></section></template>