<script setup lang="ts">
import { ref,reactive,computed,onMounted } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ArrowLeft,Save } from 'lucide-vue-next'
import { api,json } from '../../api/client'
import { useAuth } from '../../stores/auth'
import { dateInput } from '../../utils/formatDate'
import { formatMoney,toMinor,moneyFactor } from '../../utils/money'
import CurrencyPicker from '../../components/CurrencyPicker.vue'
import type { Client,Invoice,Item,Page } from '../../types'
import LineItemsEditor from '../../components/LineItemsEditor.vue'
const auth=useAuth(),route=useRoute(),router=useRouter(),id=route.params.id,clients=ref<Client[]>([]),error=ref(''),busy=ref(false),loading=ref(true),discount=ref(0)
const form=reactive({po_number:'',currency:auth.user?.business.currency||'NGN',client_id:'' as string|number,issue_date:dateInput(),due_date:dateInput(14),tax_percent:auth.user?.business.default_tax_percent||0,notes:'Thank you for your business.',terms:'Payment is due by the date shown.',items:[{description:'',quantity:1,unit_price_kobo:0}] as Item[]})
const discountMinor=computed(()=>{try{return toMinor(discount.value,form.currency)}catch{return 0}})
const subtotal=computed(()=>form.items.reduce((s,i)=>s+Math.round(i.quantity*i.unit_price_kobo),0)),tax=computed(()=>Math.round(Math.max(0,subtotal.value-discountMinor.value)*form.tax_percent/100))
onMounted(async()=>{try{
 let page=1,last=1;do{const result=await api<Page<Client>>('/clients?per_page=100&page='+page);clients.value.push(...result.data);last=result.last_page;page++}while(page<=last)
 if(id){const invoice=await api<Invoice>('/invoices/'+id);Object.assign(form,{po_number:invoice.po_number||'',currency:invoice.currency,client_id:invoice.client_id,issue_date:invoice.issue_date,due_date:invoice.due_date,tax_percent:invoice.tax_percent,notes:invoice.notes,terms:invoice.terms,items:invoice.items.map(i=>({description:i.description,quantity:i.quantity,unit:i.unit||'pcs',unit_price_kobo:i.unit_price_kobo}))});discount.value=invoice.discount_kobo/moneyFactor(invoice.currency)}
}catch(e){error.value=(e as Error).message}finally{loading.value=false}})
async function save(){busy.value=true;error.value='';try{const invoice=await api<Invoice>('/invoices'+(id?'/'+id:''),json(id?'PUT':'POST',{...form,discount_kobo:toMinor(discount.value,form.currency)}));router.push('/invoices/'+invoice.id)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function changeCurrency(currency:string){if(currency===form.currency)return;if(!confirm('Changing currency does not convert prices. Clear line prices and discount so you can enter prices in the new currency?'))return;form.currency=currency;discount.value=0;form.items.forEach(i=>i.unit_price_kobo=0)}
</script>
<template><RouterLink to="/invoices" class="back-link"><ArrowLeft :size="16"/>Back to invoices</RouterLink><div class="page-heading"><div><span class="eyebrow">MAKE YOUR WORK OFFICIAL</span><h1>{{ id?'Edit invoice':'Create invoice' }}<span class="heading-dot">.</span></h1><p class="muted">A few details now. A professional impression later.</p></div></div><p v-if="loading" class="loading">Loading invoice editor…</p><form v-else @submit.prevent="save"><div class="editor-grid"><div><section class="panel form-panel"><h2>The essentials</h2><label>Document currency<CurrencyPicker :model-value="form.currency" @update:model-value="changeCurrency"/></label><label>Bill to<select v-model="form.client_id" required><option value="" disabled>Select a client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ client.name }}{{ client.company?' · '+client.company:'' }}</option></select></label><RouterLink to="/clients/new" class="text-link">+ Add a new client</RouterLink><div class="form-grid spaced"><label>PO reference (optional)<input v-model="form.po_number" maxlength="100" placeholder="Customer purchase order number"></label><label>Issue date<input v-model="form.issue_date" type="date" required></label><label>Due date<input v-model="form.due_date" type="date" :min="form.issue_date" required></label></div></section><section class="panel form-panel spaced"><h2>What’s on the invoice?</h2><LineItemsEditor v-model="form.items" :currency="form.currency"/></section><section class="panel form-panel spaced"><h2>A personal touch</h2><label>Notes<textarea v-model="form.notes" rows="3"/></label><label>Terms<textarea v-model="form.terms" rows="2"/></label></section></div><aside><section class="panel form-panel summary" aria-live="polite"><span class="eyebrow">INVOICE SUMMARY</span><h2>The numbers</h2><label>Discount ({{ form.currency }})<input v-model.number="discount" type="number" min="0" :max="subtotal/moneyFactor(form.currency)" :step="1/moneyFactor(form.currency)"></label><label>Tax (%)<input v-model.number="form.tax_percent" type="number" min="0" max="100" step=".01" required></label><div class="total-row"><span>Subtotal</span><strong>{{ formatMoney(subtotal,form.currency) }}</strong></div><div class="total-row"><span>Discount</span><span>− {{ formatMoney(discountMinor,form.currency) }}</span></div><div class="total-row"><span>Tax</span><span>{{ formatMoney(tax,form.currency) }}</span></div><div class="total-row grand-total"><span>Total</span><strong>{{ formatMoney(Math.max(0,subtotal-discountMinor)+tax,form.currency) }}</strong></div><p class="muted">Saved as a draft. Review and send when you’re ready.</p><button class="button primary wide" :disabled="busy||!clients.length"><Save :size="16"/>{{ busy?'Saving…':'Save invoice' }}</button><RouterLink to="/invoices" class="button ghost wide">Cancel</RouterLink></section></aside></div><p v-if="error" class="error" role="alert">{{ error }}</p></form></template>