<script setup lang="ts">
import { ref,reactive,onMounted,computed } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api,json } from '../../api/client'
import { useAuth } from '../../stores/auth'
import { dateInput } from '../../utils/formatDate'
import { toMinor,moneyFactor,formatMoney } from '../../utils/money'
import LineItemsEditor from '../../components/LineItemsEditor.vue'
import CurrencyPicker from '../../components/CurrencyPicker.vue'
import type { Item,Client,Page,CommercialDocument } from '../../types'
const route=useRoute(),router=useRouter(),auth=useAuth(),kind=computed(()=>String(route.meta.documentKind)),quote=computed(()=>kind.value==='quotations'),clients=ref<Client[]>([]),discount=ref(0),error=ref(''),ready=ref(false),busy=ref(false)
const form=reactive({client_id:'' as string|number,currency:auth.user?.business.currency||'NGN',issue_date:dateInput(),due_date:dateInput(14),tax_percent:auth.user?.business.default_tax_percent||0,notes:'',terms:'',delivery_address:'',items:[{description:'',quantity:1,unit:'pcs',unit_price_kobo:0}] as Item[]})
onMounted(async()=>{try{let n=1,last=1;do{const result=await api<Page<Client>>('/clients?per_page=100&page='+n);clients.value.push(...result.data);last=result.last_page;n++}while(n<=last);if(route.params.id){const d=await api<CommercialDocument>('/documents/'+kind.value+'/'+route.params.id);Object.assign(form,{client_id:d.client_id,currency:d.currency,issue_date:d.issue_date,due_date:d.due_date,tax_percent:d.tax_percent,notes:d.notes||'',terms:d.terms||'',delivery_address:d.delivery_address||'',items:d.items.map(i=>({description:i.description,unit:i.unit,quantity:i.quantity,unit_price_kobo:i.unit_price_kobo}))});discount.value=d.discount_kobo/moneyFactor(d.currency)}ready.value=true}catch(e){error.value=(e as Error).message}})
const subtotal=computed(()=>form.items.reduce((n,i)=>n+Math.round(i.unit_price_kobo*i.quantity),0))
const discountMinor=computed(()=>{try{return toMinor(discount.value,form.currency)}catch{return 0}}),tax=computed(()=>Math.round(Math.max(0,subtotal.value-discountMinor.value)*Number(form.tax_percent||0)/100)),total=computed(()=>Math.max(0,subtotal.value-discountMinor.value)+tax.value)
async function save(){busy.value=true;error.value='';try{const d=await api<CommercialDocument>('/documents/'+kind.value+(route.params.id?'/'+route.params.id:''),json(route.params.id?'PUT':'POST',{...form,discount_kobo:quote.value?toMinor(discount.value,form.currency):0,tax_percent:quote.value?form.tax_percent:0}));router.push('/'+kind.value+'/'+d.id)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function currency(code:string){if(code===form.currency)return;if(!confirm('Changing currency clears prices and discount. No exchange-rate conversion is applied.'))return;form.currency=code;discount.value=0;form.items.forEach(i=>i.unit_price_kobo=0)}
</script>
<template><RouterLink :to="'/'+kind" class="back-link">Back to {{ kind==='quotations'?'quotations':'delivery notes' }}</RouterLink><h1>{{ route.params.id?'Edit':'Create' }} {{ quote?'quotation':'delivery note' }}</h1><p v-if="error" class="error" role="alert">{{ error }}</p><form v-if="ready" class="panel admin-panel" @submit.prevent="save"><div class="form-grid"><label>Client<select v-model="form.client_id" required><option value="" disabled>Select a client</option><option v-for="c in clients" :key="c.id" :value="c.id">{{ c.name }}</option></select></label><label v-if="quote">Currency<CurrencyPicker :model-value="form.currency" @update:model-value="currency"/></label><label>Issue date<input v-model="form.issue_date" type="date" required></label><label>{{ quote?'Valid until':'Delivery date' }}<input v-model="form.due_date" type="date" :min="form.issue_date" required></label></div><RouterLink to="/clients/new">Add a client</RouterLink><label v-if="!quote" class="spaced">Delivery address<textarea v-model="form.delivery_address" maxlength="2000"/></label><h2 class="spaced">{{ quote?'Items offered':'Items delivered' }}</h2><LineItemsEditor v-model="form.items" :currency="form.currency" :quantities-only="!quote"/><div v-if="quote" class="form-grid spaced"><label>Discount ({{ form.currency }})<input v-model.number="discount" type="number" min="0" :step="1/moneyFactor(form.currency)" :max="subtotal/moneyFactor(form.currency)"></label><label>Tax (%)<input v-model.number="form.tax_percent" type="number" min="0" max="100" step=".01"></label></div><div v-if="quote" class="panel form-panel spaced" aria-live="polite"><div class="total-row"><span>Subtotal</span><strong>{{ formatMoney(subtotal,form.currency) }}</strong></div><div class="total-row"><span>Discount</span><strong>− {{ formatMoney(discountMinor,form.currency) }}</strong></div><div class="total-row"><span>Tax</span><strong>{{ formatMoney(tax,form.currency) }}</strong></div><div class="total-row grand-total"><span>Total</span><strong>{{ formatMoney(total,form.currency) }}</strong></div></div><label class="spaced">Notes<textarea v-model="form.notes" maxlength="5000"/></label><label>Terms<textarea v-model="form.terms" maxlength="5000"/></label><p class="muted">{{ quote?'This is an offer, not a payment receipt.':'Delivery notes show quantities only. They do not update stock or record payment.' }}</p><button class="button primary" :disabled="busy||!clients.length">{{ busy?'Saving…':'Save draft' }}</button></form></template>
