<script setup lang="ts">
import { ref,onMounted,computed } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api,json,downloadFile } from '../../api/client'
import { useAuth } from '../../stores/auth'
import { formatMoney } from '../../utils/money'
import { formatDate } from '../../utils/formatDate'
import type { CommercialDocument,Invoice } from '../../types'
const route=useRoute(),router=useRouter(),auth=useAuth(),kind=computed(()=>String(route.meta.documentKind)),d=ref<CommercialDocument>(),error=ref(''),busy=ref(false),received=ref('')
async function load(){d.value=await api('/documents/'+kind.value+'/'+route.params.id)}
async function run(fn:()=>Promise<void>){busy.value=true;error.value='';try{await fn()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
onMounted(()=>run(load))
async function transition(action:string){await run(async()=>{d.value=await api('/documents/'+kind.value+'/'+d.value!.id+'/transition',json('POST',{action,received_by:received.value}))})}
async function convert(){await run(async()=>{const i=await api<Invoice>('/documents/'+kind.value+'/'+d.value!.id+'/convert',json('POST',{}));router.push('/invoices/'+i.id)})}
</script>
<template><RouterLink :to="'/'+kind" class="back-link">Back to list</RouterLink><p v-if="error" class="error" role="alert">{{ error }}</p><template v-if="d"><div class="page-heading"><div><h1>{{ d.number }}</h1><p>{{ d.kind==='quotation'?'Quotation':'Delivery note' }} · {{ d.status }}</p></div><button class="button secondary" :disabled="busy" @click="run(()=>downloadFile('/documents/'+kind+'/'+d!.id+'/pdf',d!.number+'.pdf'))">Download PDF</button></div><section class="panel admin-panel"><h2>{{ d.client.name }}</h2><p>Issued {{ formatDate(d.issue_date) }} · {{ d.kind==='quotation'?'Valid until':'Delivery date' }} {{ formatDate(d.due_date) }}</p><p v-if="d.delivery_address">{{ d.delivery_address }}</p><div class="table-scroll"><table><thead><tr><th>Description</th><th>Quantity</th><th>Unit</th><th v-if="d.kind==='quotation'">Amount</th></tr></thead><tbody><tr v-for="(item,n) in d.items" :key="n"><td>{{ item.description }}</td><td>{{ item.quantity }}</td><td>{{ item.unit }}</td><td v-if="d.kind==='quotation'">{{ formatMoney(item.line_total_kobo||0,d.currency,d.currency_minor_units) }}</td></tr></tbody></table></div><h2 v-if="d.kind==='quotation'">Total {{ formatMoney(d.total_kobo,d.currency,d.currency_minor_units) }}</h2><p>{{ d.notes }}</p><p>{{ d.terms }}</p><p v-if="d.received_by">Received by {{ d.received_by }}</p><div class="admin-filter"><RouterLink v-if="d.status==='draft'" :to="'/'+kind+'/'+d.id+'/edit'" class="button secondary">Edit draft</RouterLink><button v-if="d.status==='draft'" class="button primary" :disabled="busy" @click="transition('issue')">Issue document</button><template v-if="auth.manager&&d.kind==='quotation'&&d.status==='issued'"><button class="button primary" :disabled="busy" @click="transition('accept')">Record acceptance</button><button class="button secondary" :disabled="busy" @click="transition('decline')">Record decline</button></template><button v-if="auth.manager&&d.kind==='quotation'&&d.status==='accepted'" class="button primary" :disabled="busy" @click="convert">Convert to invoice</button><RouterLink v-if="d.invoice_id" :to="'/invoices/'+d.invoice_id" class="button secondary">View linked invoice</RouterLink><template v-if="auth.manager&&d.kind==='delivery_note'&&d.status==='issued'"><label>Received by<input v-model="received" maxlength="150" placeholder="Recipient name"></label><button class="button primary" :disabled="busy||!received" @click="transition('deliver')">Record delivered</button></template></div><p class="muted">Acceptance and receipt are recorded by your team. They are not customer electronic signatures.</p></section></template></template>
