<script setup lang="ts">
import { ref,watch } from 'vue'
import { Plus,Trash2 } from 'lucide-vue-next'
import type { Item,Product,Page } from '../types'
import { currencyDigits,formatMoney,toMinor,moneyFactor } from '../utils/money'
import { api } from '../api/client'
const props=withDefaults(defineProps<{currency?:string;quantitiesOnly?:boolean}>(),{currency:'NGN',quantitiesOnly:false})
const items=defineModel<Item[]>({required:true}),products=ref<Product[]>([]),query=ref(''),error=ref(''),selected=ref('')
function add(){items.value.push({description:'',quantity:1,unit:'pcs',unit_price_kobo:0})}
function price(event:Event,item:Item){try{item.unit_price_kobo=toMinor((event.target as HTMLInputElement).value||'0',props.currency);error.value=''}catch(e){error.value=(e as Error).message}}
async function search(){try{const p=await api<Page<Product>>('/products?active=1&per_page=100&'+(props.quantitiesOnly?'':'currency='+props.currency+'&')+'search='+encodeURIComponent(query.value));products.value=p.data;error.value=''}catch(e){error.value=(e as Error).message}}
watch(()=>props.currency,search,{immediate:true})
function choose(){const p=products.value.find(x=>x.id===Number(selected.value));if(!p)return;const line={description:p.name+(p.description?' — '+p.description:''),unit:p.unit,quantity:1,unit_price_kobo:props.quantitiesOnly?0:p.unit_price_minor};line.description=line.description.slice(0,255);if(items.value.length===1&&!items.value[0]!.description)items.value[0]=line;else items.value.push(line);selected.value=''}
</script>
<template><div class="line-items-editor"><div class="admin-filter"><label>Find a product<input v-model="query" @keydown.enter.prevent="search" placeholder="Name or SKU"></label><button class="button secondary" type="button" @click="search">Search catalogue</button><label>Add from catalogue<select v-model="selected" @change="choose"><option value="">Choose a product</option><option v-for="p in products" :key="p.id" :value="p.id">{{ p.sku }} · {{ p.name }}</option></select></label></div><p v-if="error" class="error">{{ error }}</p><div class="table-wrap"><table class="line-editor"><thead><tr><th>Description</th><th>Quantity</th><th>Unit</th><template v-if="!quantitiesOnly"><th>Rate ({{ currency }})</th><th>Amount</th></template><th></th></tr></thead><tbody><tr v-for="(item,index) in items" :key="index"><td><input v-model="item.description" required maxlength="255" placeholder="Service or product description"></td><td><input v-model.number="item.quantity" type="number" min=".01" max="100000" step=".01" required></td><td><input v-model="item.unit" maxlength="30" placeholder="pcs"></td><template v-if="!quantitiesOnly"><td><input :value="item.unit_price_kobo/moneyFactor(currency)" @input="price($event,item)" aria-label="Unit price" type="number" min="0" :step="1/moneyFactor(currency)" required></td><td class="money">{{ formatMoney(Math.round(item.quantity*item.unit_price_kobo),currency,currencyDigits(currency)) }}</td></template><td><button type="button" class="icon-button danger-text" :disabled="items.length===1" @click="items.splice(index,1)" aria-label="Remove line"><Trash2 :size="17"/></button></td></tr></tbody></table></div><button type="button" class="button ghost" @click="add"><Plus :size="16"/>Add manual line</button></div></template>
