<script setup lang="ts">
import { ref,onMounted } from 'vue'
import { Save,Upload } from 'lucide-vue-next'
import { api,json } from '../../api/client'
import { useRouter } from 'vue-router'
import { useAuth } from '../../stores/auth'
import type { Business } from '../../types'
const router=useRouter(),auth=useAuth(),form=ref<Business|null>(null),error=ref(''),success=ref(''),busy=ref(false),uploading=ref(false),logoBroken=ref(false)
onMounted(async()=>{try{form.value=await api<Business>('/business')}catch(e){error.value=(e as Error).message}})
async function save(){busy.value=true;error.value='';try{form.value=await api<Business>('/business',json('PUT',form.value));if(auth.user)auth.user.business=form.value;success.value='Your business settings are saved.'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function removeBusiness(){
 const name=prompt('Permanently delete this business and all its invoices, clients, payments and accounts? Type the exact business name to confirm.')
 if(name===null)return
 if(name!==form.value?.name){error.value='Business name does not match.';return}
 busy.value=true
 try{await api('/business',json('DELETE',{business_name:name}));localStorage.removeItem('invoice_token');auth.user=null;router.push('/login')}catch(e){error.value=(e as Error).message}finally{busy.value=false}
}
async function logo(event:Event){error.value='';success.value='';logoBroken.value=false;const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const body=new FormData();body.append('logo',file);uploading.value=true;try{form.value=await api<Business>('/business/logo',{method:'POST',body});if(auth.user)auth.user.business=form.value;success.value='Logo updated.'}catch(e){error.value=(e as Error).message}finally{uploading.value=false;(event.target as HTMLInputElement).value=''}}
</script>
<template><div class="page-heading"><div><span class="eyebrow">MAKE IT YOURS</span><h1>Business settings<span class="heading-dot">.</span></h1><p class="muted">Your details. Your brand. On every invoice.</p></div></div><p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="success" class="success" role="status">{{ success }}</p><form v-if="form" @submit.prevent="save" class="editor-grid"><div><section class="panel form-panel"><h2>Business details</h2><label>Business name<input v-model="form.name" required></label><div class="form-grid"><label>Billing email<input v-model="form.email" type="email"></label><label>Phone number<input v-model="form.phone"></label></div><label>Address<textarea v-model="form.address" rows="2"/></label></section><section class="panel form-panel spaced"><h2>Invoice defaults</h2><div class="form-grid"><label>Invoice prefix<input v-model="form.invoice_prefix" required maxlength="15"></label><label>Default tax (%)<input v-model.number="form.default_tax_percent" type="number" min="0" max="100" step=".01" required></label><label>Currency<select v-model="form.currency"><option value="NGN">NGN · Nigerian naira</option></select></label></div><label>Payment instructions<textarea v-model="form.payment_instructions" rows="4" placeholder="Bank name, account number, and account holder"/></label><div class="form-actions"><button class="button primary" :disabled="busy"><Save :size="16"/>{{ busy?'Saving…':'Save settings' }}</button></div></section></div><aside><section class="panel form-panel"><span class="eyebrow">YOUR BRAND</span><h2>A familiar face.</h2><div class="logo-preview"><img v-if="form.logo_url&&!logoBroken" :src="form.logo_url" alt="Business logo" @error="logoBroken=true"><span v-else>{{ form.name.slice(0,2).toUpperCase() }}</span></div><p v-if="logoBroken" class="error">The saved logo could not be loaded. Try uploading it again.</p><label class="button secondary upload-label"><Upload :size="16"/>{{ uploading?'Uploading...':'Upload logo' }}<input type="file" accept="image/png,image/jpeg" :disabled="uploading" @change="logo"></label><small class="muted">PNG or JPG, up to 1 MB.</small><label class="spaced">Brand colour<div class="color-control"><input v-model="form.brand_color" type="color"><input v-model="form.brand_color" pattern="#[a-fA-F0-9]{6}" required></div></label><p class="muted">Used on your invoice PDF and public invoice page.</p></section><section v-if="auth.user?.role==='owner'" class="panel form-panel spaced"><h2>Delete business</h2><p class="muted">Permanently removes this workspace, all invoices, clients, payments, and team accounts.</p><button type="button" class="button secondary danger-text wide spaced" :disabled="busy" @click="removeBusiness">Delete business permanently</button></section></aside></form></template>