<script setup lang="ts">
import { onMounted,reactive,ref } from 'vue'
import { api,json } from '../../api/client'
type Page<T>={data:T[],current_page:number,last_page:number,total:number}
type User={id:number,name:string,email:string,role:string,is_platform_admin:boolean,business?:{name:string},created_at:string,last_login_at:string|null,last_seen_at:string|null}
type Activity={id:number,user_id:number|null,user?:{name:string,email:string},event:string,status_code:number|null,created_at:string}
type Delivery={id:number,recipient:string,kind:string,status:string,attempts:number,error:string|null,created_at:string}
type Settings=Record<string,string|number|boolean>
type Field={key:string,label:string,type?:string,options?:string[]}
const tabs=['Overview','Users','Activity','Integrations','Payment emails','Advertising'],tab=ref('Overview'),busy=ref(false),ready=ref(false),message=ref(''),error=ref('')
const overview=ref<{users:number,businesses:number,active_last_5_minutes:number,timezone:string,daily:{date:string,logged_in_users:number,new_users:number}[]}|null>(null)
const users=ref<Page<User>>(),activity=ref<Page<Activity>>(),deliveries=ref<Page<Delivery>>()
const search=ref(''),activityUser=ref(''),recipient=ref(''),settings=reactive<Settings>({}),ads=reactive({enabled:false,approved:false,consent_ready:false,publisher_id:'',slot_id:''})
const secrets=['smtp_password','cloudinary_api_key','cloudinary_api_secret','whatsapp_token']
const groups:{title:string,fields:Field[]}[]=[
 {title:'Email delivery',fields:[{key:'mail_driver',label:'Delivery mode',options:['log','smtp']},{key:'smtp_host',label:'SMTP host'},{key:'smtp_port',label:'SMTP port',type:'number'},{key:'smtp_security',label:'SMTP security',options:['tls','ssl']},{key:'smtp_username',label:'SMTP username'},{key:'smtp_password',label:'SMTP password',type:'password'},{key:'mail_from_address',label:'Sender email',type:'email'},{key:'mail_from_name',label:'Sender name'},{key:'payment_owner_email',label:'Email business owners when a payment is recorded',type:'checkbox'},{key:'payment_client_email',label:'Email customers a payment receipt',type:'checkbox'}]},
 {title:'Image storage',fields:[{key:'media_driver',label:'Image storage',options:['local','cloudinary']},{key:'cloudinary_cloud_name',label:'Cloudinary cloud name'},{key:'cloudinary_api_key',label:'Cloudinary API key',type:'password'},{key:'cloudinary_api_secret',label:'Cloudinary API secret',type:'password'},{key:'cloudinary_folder',label:'Cloudinary folder'}]},
 {title:'WhatsApp',fields:[{key:'whatsapp_enabled',label:'Enable WhatsApp delivery',type:'checkbox'},{key:'whatsapp_phone_id',label:'WhatsApp phone number ID'},{key:'whatsapp_token',label:'WhatsApp access token',type:'password'},{key:'whatsapp_version',label:'Graph API version'}]}
]
function applySettings(result:Settings){Object.assign(settings,result);for(const key of secrets){settings[key]='';settings['clear_'+key]=false}}
async function userPage(page=1){users.value=await api('/platform/users?page='+page+'&search='+encodeURIComponent(search.value))}
async function activityPage(page=1){activity.value=await api('/platform/activity?page='+page+(activityUser.value?'&user_id='+encodeURIComponent(activityUser.value):''))}
async function deliveryPage(page=1){deliveries.value=await api('/platform/payment-emails?page='+page)}
async function run(action:()=>Promise<void>){busy.value=true;error.value='';message.value='';try{await action()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function load(){await run(async()=>{const [summary,config,advertising]=await Promise.all([api<typeof overview.value>('/platform/overview'),api<Settings>('/platform/integrations'),api<typeof ads>('/advertising')]);overview.value=summary;applySettings(config);Object.assign(ads,advertising);await Promise.all([userPage(),activityPage(),deliveryPage()]);ready.value=true})}
onMounted(load)
async function save(){await run(async()=>{const payload={...settings};for(const key of secrets)delete payload['has_'+key];applySettings(await api<Settings>('/platform/integrations',json('PUT',payload)));message.value='Saved. Requests and queued jobs use these settings; .env stays as the installation fallback.'})}
async function test(kind:string){await run(async()=>{const result=await api<{message:string}>('/platform/integrations/test/'+kind,json('POST',kind==='smtp'?{recipient:recipient.value}:{}));message.value=result.message})}
async function saveAds(){await run(async()=>{Object.assign(ads,await api('/platform/advertising',json('PUT',ads)));message.value='Advertising settings saved. Ads require consent from your integrated consent manager.'})}
async function retry(id:number){await run(async()=>{const result=await api<{message:string}>('/platform/payment-emails/'+id+'/retry',json('POST',{}));message.value=result.message;await deliveryPage(deliveries.value?.current_page)})}
const date=(value:string|null)=>value?new Date(value).toLocaleString('en-NG',{timeZone:'Africa/Lagos'}):'—'
</script>
<template><div class="page-heading"><div><span class="eyebrow">NEXAIBYTE PLATFORM</span><h1>Platform administration</h1><p class="muted">Manage this free service across all business workspaces.</p></div><RouterLink class="button secondary" to="/platform">Branding & favicon upload</RouterLink></div>
<p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="message" class="success" role="status">{{ message }}</p><button v-if="!ready" class="button secondary" :disabled="busy" @click="load">Load administration</button>
<template v-if="ready"><nav class="admin-tabs" aria-label="Admin sections"><button v-for="item in tabs" :key="item" :class="['button',tab===item?'primary':'secondary']" @click="tab=item">{{ item }}</button></nav>
<section v-if="tab==='Overview'&&overview" class="panel admin-panel"><h2>Service usage</h2><div class="admin-stats"><p><strong>{{ overview.users }}</strong> registered users</p><p><strong>{{ overview.businesses }}</strong> business workspaces</p><p><strong>{{ overview.active_last_5_minutes }}</strong> active in the last 5 minutes</p></div><p class="muted">Daily distinct users who signed in or registered. Times use {{ overview.timezone }}. Recent activity is an estimate, not a count of open browser windows.</p><div class="table-scroll"><table><thead><tr><th>Date</th><th>Users who logged in</th><th>New users</th></tr></thead><tbody><tr v-for="day in overview.daily.slice().reverse()" :key="day.date"><td>{{ day.date }}</td><td>{{ day.logged_in_users }}</td><td>{{ day.new_users }}</td></tr></tbody></table></div><button class="button secondary" :disabled="busy" @click="run(async()=>{overview=await api('/platform/overview')})">Refresh statistics</button></section>
<section v-if="tab==='Users'" class="panel admin-panel"><h2>Registered users</h2><form class="admin-filter" @submit.prevent="run(()=>userPage())"><label>Name or email<input v-model="search" maxlength="100"></label><button class="button secondary" :disabled="busy">Search</button></form><div class="table-scroll"><table><thead><tr><th>User</th><th>Business</th><th>Access</th><th>Registered</th><th>Last login</th><th>Last activity</th></tr></thead><tbody><tr v-for="u in users?.data" :key="u.id"><td>{{ u.name }}<br><small>{{ u.email }} · #{{ u.id }}</small></td><td>{{ u.business?.name }}</td><td>{{ u.role }}{{ u.is_platform_admin?' · Platform admin':'' }}</td><td>{{ date(u.created_at) }}</td><td>{{ date(u.last_login_at) }}</td><td>{{ date(u.last_seen_at) }}</td></tr></tbody></table></div><div v-if="users" class="admin-pagination"><button class="button secondary" :disabled="busy||users.current_page===1" @click="run(()=>userPage(users!.current_page-1))">Previous</button><span>{{ users.total }} users · Page {{ users.current_page }} of {{ users.last_page }}</span><button class="button secondary" :disabled="busy||users.current_page===users.last_page" @click="run(()=>userPage(users!.current_page+1))">Next</button></div></section>
<section v-if="tab==='Activity'" class="panel admin-panel"><h2>User activity</h2><p class="muted">Sign-ins, registrations and authenticated changes. No passwords, keys or request contents are recorded. Collection starts with this update.</p><form class="admin-filter" @submit.prevent="run(()=>activityPage())"><label>Filter by user ID (optional)<input v-model="activityUser" type="number" min="1"></label><button class="button secondary" :disabled="busy">Filter</button></form><div class="table-scroll"><table><thead><tr><th>Time (Lagos)</th><th>User</th><th>Action</th><th>HTTP status</th></tr></thead><tbody><tr v-for="a in activity?.data" :key="a.id"><td>{{ date(a.created_at) }}</td><td>{{ a.user?.name||'Deleted user' }}<br><small>{{ a.user?.email }}</small></td><td>{{ a.event }}</td><td>{{ a.status_code||'—' }}</td></tr></tbody></table></div><div v-if="activity" class="admin-pagination"><button class="button secondary" :disabled="busy||activity.current_page===1" @click="run(()=>activityPage(activity!.current_page-1))">Previous</button><span>{{ activity.total }} events · Page {{ activity.current_page }}</span><button class="button secondary" :disabled="busy||activity.current_page===activity.last_page" @click="run(()=>activityPage(activity!.current_page+1))">Next</button></div></section>
<section v-if="tab==='Integrations'" class="panel admin-panel"><h2>Integrations & email</h2><p class="notice">Save changes before testing. Empty secret fields keep the stored value; select Clear to remove it. Log mode writes emails to the server log and does not deliver them.</p><form autocomplete="off" @submit.prevent="save"><fieldset v-for="group in groups" :key="group.title" :disabled="busy"><legend>{{ group.title }}</legend><div class="form-grid"><label v-for="field in group.fields" :key="field.key"><template v-if="field.type==='checkbox'"><input v-model="settings[field.key]" type="checkbox"> {{ field.label }}</template><template v-else>{{ field.label }}<select v-if="field.options" v-model="settings[field.key]"><option v-for="option in field.options" :key="option" :value="option">{{ option }}</option></select><input v-else-if="field.type==='number'" v-model.number="settings[field.key]" type="number" min="1" max="65535"><input v-else v-model="settings[field.key]" :type="field.type||'text'" :autocomplete="field.type==='password'?'new-password':'off'" :maxlength="field.type==='password'?4096:255"><template v-if="field.type==='password'"><small>{{ settings['has_'+field.key]?'A secret is configured.':'No secret configured.' }}</small><span><input v-model="settings['clear_'+field.key]" type="checkbox"> Clear stored secret</span></template></template></label></div></fieldset><button class="button primary" :disabled="busy">Save integrations</button></form><h3>Test saved settings</h3><div class="admin-filter"><label>Test email recipient<input v-model="recipient" type="email" autocomplete="off"></label><button class="button secondary" :disabled="busy||!recipient" @click="test('smtp')">Send test email</button><button class="button secondary" :disabled="busy" @click="test('cloudinary')">Test Cloudinary</button><button class="button secondary" :disabled="busy" @click="test('whatsapp')">Test WhatsApp access</button></div><p class="muted">Email tests send a real message. Provider tests authenticate only. Changing image storage does not migrate previously uploaded images.</p></section>
<section v-if="tab==='Payment emails'" class="panel admin-panel"><h2>Payment email deliveries</h2><p class="muted">The queue cron processes these notices. “Logged” means mail log mode was active; no email was delivered. Payments remain recorded even when an email fails.</p><div class="table-scroll"><table><thead><tr><th>Recorded</th><th>Recipient</th><th>Type</th><th>Status</th><th>Attempts</th><th>Action</th></tr></thead><tbody><tr v-for="d in deliveries?.data" :key="d.id"><td>{{ date(d.created_at) }}</td><td>{{ d.recipient }}</td><td>{{ d.kind }}</td><td>{{ d.status }}<br><small>{{ d.error }}</small></td><td>{{ d.attempts }}</td><td><button v-if="d.status==='failed'" class="button secondary" :disabled="busy" @click="retry(d.id)">Retry</button></td></tr></tbody></table></div><div v-if="deliveries" class="admin-pagination"><button class="button secondary" :disabled="busy||deliveries.current_page===1" @click="run(()=>deliveryPage(deliveries!.current_page-1))">Previous</button><button class="button secondary" :disabled="busy" @click="run(()=>deliveryPage(deliveries!.current_page))">Refresh</button><button class="button secondary" :disabled="busy||deliveries.current_page===deliveries.last_page" @click="run(()=>deliveryPage(deliveries!.current_page+1))">Next</button></div></section>
<section v-if="tab==='Advertising'" class="panel admin-panel"><h2>AdSense preparation</h2><p class="notice">Disabled by default. A reserved placement exists on the public About page. Before activation, obtain Google approval and integrate a certified consent manager where required. The app does not include a certified CMP.</p><form @submit.prevent="saveAds"><div class="form-grid"><label>Publisher ID<input v-model="ads.publisher_id" placeholder="ca-pub-1234567890123456" pattern="ca-pub-[0-9]{16}"></label><label>Ad unit slot ID<input v-model="ads.slot_id" inputmode="numeric" pattern="[0-9]{1,20}"></label><label><input v-model="ads.approved" type="checkbox"> Google has approved this site</label><label><input v-model="ads.consent_ready" type="checkbox"> Consent manager integration is installed and verified</label><label><input v-model="ads.enabled" type="checkbox"> Enable the public About page placement</label></div><button class="button primary" :disabled="busy">Save advertising settings</button></form><p><RouterLink to="/about">View public About page</RouterLink> · <a href="/ads.txt" target="_blank" rel="noopener">View ads.txt</a></p><p class="muted">Ads do not appear on private dashboards, invoices, client pages or signed invoice links. Revenue and site approval are controlled by Google.</p></section>
</template></template>
