<script setup lang="ts">
import { reactive,ref,onMounted } from 'vue'
import { api } from '../../api/client'
import { usePlatform,type PlatformSettings } from '../../stores/platform'
const platform=usePlatform(),form=reactive<PlatformSettings>({...platform.settings}),busy=ref(false),ready=ref(false),uploading=ref(false),error=ref(''),saved=ref('')
const fields:[keyof PlatformSettings,string][]=[['product_name','Product name'],['company_name','Company name'],['company_url','Company website'],['support_email','Support email'],['tagline','Welcome tagline'],['hero_title','Welcome headline'],['hero_description','Welcome description'],['login_title','Login heading'],['login_description','Login description'],['register_title','Registration heading'],['register_description','Registration description'],['announcement','Announcement (leave empty to hide)']]
const colors:[keyof PlatformSettings,string][]=[['primary_color','Buttons and links'],['background_color','Welcome background'],['accent_color','Welcome accents']]
async function load(){ready.value=false;await platform.load();error.value=platform.loadError;if(!error.value){Object.assign(form,platform.settings);ready.value=true}}
onMounted(load)
async function save(){busy.value=true;error.value='';saved.value='';try{await platform.save({...form});saved.value='Saved. Changes appear when visitors open or refresh the app.'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function upload(event:Event,kind:'logo'|'favicon'){
 const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;uploading.value=true;error.value='';saved.value='';
 try{const body=new FormData();body.append('image',file);const result=await api<PlatformSettings>('/platform/images/'+kind,{method:'POST',body});platform.settings=result;platform.apply();form.logo_url=result.logo_url;form.favicon_url=result.favicon_url;saved.value='Image uploaded. Your other unsaved changes are preserved.'}catch(e){error.value=(e as Error).message}finally{uploading.value=false;input.value=''}
}
function companyPalette(){form.primary_color='#007F83';form.background_color='#0B1622';form.accent_color='#F5A623'}
</script>
<template><div class="page-heading"><div><span class="eyebrow">PLATFORM ADMINISTRATION</span><h1>Branding & content</h1><p class="muted">Control the shared website for every business.</p></div></div><p v-if="error" class="error" role="alert">{{ error }}</p><button v-if="!ready" class="button secondary" @click="load">Reload settings</button><form v-if="ready" class="panel form-panel" @submit.prevent="save"><h2>Logo & browser icon</h2><div class="form-grid"><label>Product logo<img v-if="form.logo_url" :src="form.logo_url" alt="Product logo" class="brand-upload-preview"><input type="file" accept="image/png,image/jpeg" :disabled="uploading||busy" @change="upload($event,'logo')"><small>PNG or JPG, up to 1 MB.</small></label><label>Browser favicon<img v-if="form.favicon_url" :src="form.favicon_url" alt="Browser favicon" class="brand-upload-preview favicon-preview"><input type="file" accept="image/png,image/jpeg" :disabled="uploading||busy" @change="upload($event,'favicon')"><small>Square PNG or JPG, up to 1 MB. Converted to a 64 × 64 PNG.</small></label></div><div class="form-grid"><label v-for="[key,label] in fields" :key="key">{{ label }}<textarea v-if="key.includes('description')||key==='announcement'" v-model="form[key]" maxlength="500" rows="3"/><input v-else v-model="form[key]" :type="key==='support_email'?'email':key.includes('url')?'url':'text'" :required="key!=='logo_url'" :maxlength="key==='logo_url'?1000:key==='company_url'?500:key==='support_email'?255:150"></label></div><h2>Brand colours</h2><p class="muted">Choose a dark enough button colour for white text to remain readable.</p><div class="form-grid"><label v-for="[key,label] in colors" :key="key">{{ label }}<div class="color-control"><input type="color" v-model="form[key]"><input v-model="form[key]" pattern="#[0-9a-fA-F]{6}" required></div></label></div><button type="button" class="button secondary" @click="companyPalette">Use Nexaibyte palette</button><p class="notice">Uploaded images are public brand assets. Text is displayed as plain text. Customer invoice branding remains controlled by each business.</p><div class="brand-preview" :style="{background:form.background_color}"><strong>{{ form.product_name }}</strong><p :style="{color:form.accent_color}">{{ form.tagline }}</p><h2>{{ form.hero_title }}</h2><p>{{ form.hero_description }}</p><span :style="{background:form.primary_color}" class="button primary">Sign in</span></div><p v-if="saved" class="success" role="status">{{ saved }}</p><div class="form-actions"><button class="button primary" :disabled="busy||uploading">{{ busy?'Saving…':'Save platform settings' }}</button></div></form></template>
