<script setup lang="ts">
import { ref,onMounted } from 'vue'
import { Plus,Search,Pencil,Trash2,ArrowLeft,ArrowRight } from 'lucide-vue-next'
import { useClients } from '../../stores/clients'
import { useAuth } from '../../stores/auth'
import { api } from '../../api/client'
const store=useClients(),auth=useAuth(),search=ref(''),page=ref(1),error=ref(''),loading=ref(false)
async function load(reset=false){if(reset)page.value=1;loading.value=true;error.value='';try{await store.load('?search='+encodeURIComponent(search.value)+'&page='+page.value)}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function remove(id:number){if(!confirm('Remove this client? Existing invoices keep their client details.'))return;try{await api('/clients/'+id,{method:'DELETE'});await load()}catch(e){error.value=(e as Error).message}}
onMounted(()=>load())
</script>
<template><div class="page-heading"><div><span class="eyebrow">RELATIONSHIPS THAT MATTER</span><h1>Clients<span class="heading-dot">.</span></h1><p class="muted">Good business starts with good people.</p></div><RouterLink to="/clients/new" class="button primary"><Plus :size="18"/>Add client</RouterLink></div><section class="panel"><div class="panel-heading"><h2>Your address book <span class="count">{{ store.page?.total||0 }}</span></h2><form class="search-input" @submit.prevent="load(true)"><Search :size="17"/><input v-model="search" placeholder="Search clients…" aria-label="Search clients"><button class="button small secondary">Search</button></form></div><p v-if="error" class="error">{{ error }}</p><div v-if="loading" class="loading">Loading clients…</div><div v-else class="table-wrap"><table><thead><tr><th>Client</th><th>Email</th><th>Phone</th><th>Actions</th></tr></thead><tbody><tr v-for="client in store.page?.data" :key="client.id"><td><strong>{{ client.name }}</strong><small>{{ client.company||'Individual client' }}</small></td><td>{{ client.email||'—' }}</td><td>{{ client.phone||'—' }}</td><td><div class="actions"><RouterLink :to="'/clients/'+client.id+'/edit'" class="icon-button" aria-label="Edit client"><Pencil :size="16"/></RouterLink><button v-if="auth.manager" class="icon-button danger-text" @click="remove(client.id)" aria-label="Delete client"><Trash2 :size="16"/></button></div></td></tr><tr v-if="!store.page?.data.length"><td colspan="4" class="empty">No clients yet. Add your first client or try a different search.</td></tr></tbody></table></div><div v-if="store.page" class="pagination"><span>{{ store.page.total }} clients · Page {{ store.page.current_page }} of {{ store.page.last_page }}</span><div class="actions"><button class="button secondary small" :disabled="page===1" @click="page--;load()"><ArrowLeft :size="15"/>Previous</button><button class="button secondary small" :disabled="page>=store.page.last_page" @click="page++;load()">Next<ArrowRight :size="15"/></button></div></div></section></template>