<!doctype html><html><head><meta charset="utf-8"><title>{{ $invoice->number }}</title>
<style>
body{font-family:DejaVu Sans,sans-serif;font-size:11px;color:#243342;margin:12px}h1{font-size:28px;margin:0;color:{{ $business->brand_color }}}h2{font-size:16px}p{line-height:1.6;white-space:pre-line}.muted{color:#687783}.header{width:100%;margin-bottom:20px}.right{text-align:right}.stamp{display:inline-block;padding:8px 12px;background:#ecf7f4;color:{{ $business->brand_color }};font-weight:bold;text-transform:uppercase}.items{width:100%;border-collapse:collapse;margin-top:28px}.items th{background:{{ $business->brand_color }};color:#fff;padding:12px;text-align:left}.items td{padding:10px;border-bottom:1px solid #e2e8ed}.totals{width:46%;margin-left:54%;margin-top:22px}.totals td{padding:7px}.grand{font-size:15px;font-weight:bold;background:#eff6f4}.footer{margin-top:24px;border-top:1px solid #dae2e8;padding-top:20px}.logo{max-height:65px;max-width:170px}
</style></head><body>
<table class="header"><tr><td>@if($logo)<img class="logo" src="{{ $logo }}">@endif<h2>{{ $business->name }}</h2><p class="muted">{{ $business->address }}<br>{{ $business->email }} · {{ $business->phone }}</p></td><td class="right"><h1>INVOICE</h1><h2>{{ $invoice->number }}</h2><span class="stamp">{{ str_replace('_',' ',$invoice->status) }}</span></td></tr></table>
<table style="width:100%"><tr><td><div class="muted">BILL TO</div><h2>{{ $invoice->client->name }}</h2><p>{{ $invoice->client->company }}<br>{{ $invoice->client->address }}<br>{{ $invoice->client->email }}</p></td><td class="right"><p>Issued: {{ $invoice->issue_date->format('d M Y') }}<br>Due: {{ $invoice->due_date->format('d M Y') }}<br>Currency: {{ $invoice->currency }}</p></td></tr></table>
<table class="items"><thead><tr><th>Description</th><th>Qty</th><th>Rate ({{ $invoice->currency }})</th><th>Amount ({{ $invoice->currency }})</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->quantity }} {{ $item->unit }}</td><td>{{ app(\App\Services\CurrencyService::class)->format($item->unit_price_kobo,$invoice->currency,$invoice->currency_minor_units) }}</td><td>{{ app(\App\Services\CurrencyService::class)->format($item->line_total_kobo,$invoice->currency,$invoice->currency_minor_units) }}</td></tr>@endforeach</tbody></table>
<table class="totals">@foreach(['Subtotal'=>'subtotal_kobo','Discount'=>'discount_kobo','Tax ('.$invoice->tax_percent.'%)'=>'tax_kobo','Total'=>'total_kobo','Amount paid'=>'amount_paid_kobo','Balance due'=>'balance_kobo'] as $label=>$field)<tr @if($field==='balance_kobo')class="grand"@endif><td>{{ $label }}</td><td class="right">{{ app(\App\Services\CurrencyService::class)->format($invoice->$field,$invoice->currency,$invoice->currency_minor_units) }}</td></tr>@endforeach</table>
<div class="footer"><h2>Payment instructions</h2>@include('pdf.bank-accounts',['visibility'=>'show_on_invoice'])<p>{{ $business->payment_instructions ?: 'Please contact us for payment details.' }}</p>@if($invoice->notes)<h2>Notes</h2><p>{{ $invoice->notes }}</p>@endif @if($invoice->terms)<h2>Terms</h2><p>{{ $invoice->terms }}</p>@endif<p class="muted">Thank you for your business.</p></div>
</body></html>