<script setup lang="ts">
import { ref,reactive,onMounted } from 'vue'
import { UserPlus,Trash2,X } from 'lucide-vue-next'
import { api,json } from '../../api/client'
import { useAuth } from '../../stores/auth'
import type { User } from '../../types'
const auth=useAuth(),members=ref<User[]>([]),open=ref(false),error=ref(''),busy=ref(false),form=reactive({name:'',email:'',password:'',role:'staff'})
async function load(){try{members.value=await api<User[]>('/team')}catch(e){error.value=(e as Error).message}}
onMounted(load)
async function add(){busy.value=true;try{await api('/team',json('POST',form));open.value=false;Object.assign(form,{name:'',email:'',password:'',role:'staff'});await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function change(id:number,event:Event){try{await api('/team/'+id,json('PATCH',{role:(event.target as HTMLSelectElement).value}));await load()}catch(e){error.value=(e as Error).message;await load()}}
async function remove(id:number){if(!confirm('Remove this member’s access? Their invoice and payment history will be preserved.'))return;try{await api('/team/'+id,{method:'DELETE'});await load()}catch(e){error.value=(e as Error).message}}
</script>
<template><div class="page-heading"><div><span class="eyebrow">BETTER, TOGETHER</span><h1>Your team<span class="heading-dot">.</span></h1><p class="muted">The right people. The right access.</p></div><button class="button primary" @click="open=true;error=''"><UserPlus :size="17"/>Add team member</button></div><p v-if="error" class="error" role="alert">{{ error }}</p><section class="panel"><div class="panel-heading"><h2>Workspace members <span class="count">{{ members.length }}</span></h2></div><div class="table-wrap"><table><thead><tr><th>Member</th><th>Email</th><th>Role</th><th></th></tr></thead><tbody><tr v-for="member in members" :key="member.id"><td><div class="member-cell"><span class="avatar">{{ member.name.split(' ').map(s=>s[0]).join('') }}</span><strong>{{ member.name }}{{ member.id===auth.user?.id?' (you)':'' }}</strong></div></td><td>{{ member.email }}</td><td><select v-if="member.role!=='owner'&&member.id!==auth.user?.id" :value="member.role" @change="change(member.id,$event)" aria-label="Member role"><option value="staff">Staff</option><option value="admin">Admin</option></select><span v-else class="chip">{{ member.role }}</span></td><td><button v-if="member.role!=='owner'&&member.id!==auth.user?.id" class="icon-button danger-text" @click="remove(member.id)" aria-label="Remove member"><Trash2 :size="17"/></button></td></tr></tbody></table></div></section><div class="permission-cards"><div class="panel"><h3>Owner</h3><p class="muted">Full access to your business and its workspace.</p></div><div class="panel"><h3>Admin</h3><p class="muted">Manages settings, members, invoices, and payments.</p></div><div class="panel"><h3>Staff</h3><p class="muted">Creates clients and invoices, sends invoices, and records payments.</p></div></div><div v-if="open" class="modal-overlay" @click.self="open=false"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="team-title"><header><h2 id="team-title">Add a team member</h2><button class="icon-button" @click="open=false" aria-label="Close"><X/></button></header><p class="muted">Create their account and share these credentials securely.</p><form @submit.prevent="add"><label>Full name<input v-model="form.name" required></label><label>Email<input v-model="form.email" type="email" required></label><label>Initial password<input v-model="form.password" type="password" minlength="8" required autocomplete="new-password"></label><label>Role<select v-model="form.role"><option value="staff">Staff</option><option value="admin">Admin</option></select></label><p v-if="error" class="error">{{ error }}</p><footer><button type="button" class="button secondary" @click="open=false">Cancel</button><button class="button primary" :disabled="busy">{{ busy?'Creating…':'Create member' }}</button></footer></form></section></div></template>