<script setup lang="ts">
import { ref,reactive,onMounted } from 'vue'
import { api,json,downloadFile } from '../../api/client'
import { useAuth } from '../../stores/auth'
import { formatMoney,toMinor,moneyFactor } from '../../utils/money'
import type { Product,Page } from '../../types'
import CurrencyPicker from '../../components/CurrencyPicker.vue'
const auth=useAuth(),products=ref<Page<Product>>(),search=ref(''),error=ref(''),message=ref(''),busy=ref(false),editId=ref<number|null>(null),showForm=ref(false)
const form=reactive({sku:'',name:'',description:'',unit:'pcs',unit_price:'0',currency:auth.user?.business.currency||'NGN',is_active:true})
const file=ref<File|null>(null),updateExisting=ref(false),preview=ref<{rows:Record<string,unknown>[],errors:{row:number,message:string}[],can_import:boolean,create_count:number,update_count:number}|null>(null)
async function run(fn:()=>Promise<void>){busy.value=true;error.value='';message.value='';try{await fn()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function load(page=1){products.value=await api('/products?page='+page+'&search='+encodeURIComponent(search.value))}
onMounted(()=>run(()=>load()))
function edit(p?:Product){editId.value=p?.id??null;showForm.value=true;Object.assign(form,p?{sku:p.sku,name:p.name,description:p.description||'',unit:p.unit,unit_price:String(p.unit_price_minor/moneyFactor(p.currency)),currency:p.currency,is_active:p.is_active}:{sku:'',name:'',description:'',unit:'pcs',unit_price:'0',currency:auth.user?.business.currency||'NGN',is_active:true})}
async function save(){await run(async()=>{toMinor(form.unit_price,form.currency);await api('/products'+(editId.value?'/'+editId.value:''),json(editId.value?'PUT':'POST',form));showForm.value=false;await load();message.value='Product saved. Existing document lines remain unchanged.'})}
function selectFile(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]??null;preview.value=null}
async function importFile(confirm=false){if(!file.value)return;await run(async()=>{const body=new FormData();body.append('file',file.value!);body.append('preview',confirm?'0':'1');body.append('update_existing',updateExisting.value?'1':'0');if(confirm){const result=await api<{created:number,updated:number}>('/products/import',{method:'POST',body});message.value=`Imported ${result.created} products; updated ${result.updated}.`;preview.value=null;await load()}else preview.value=await api('/products/import',{method:'POST',body})})}
async function template(format:string){await run(()=>downloadFile('/products/template/'+format,'products-template.'+format))}
</script>
<template><div class="page-heading"><div><span class="eyebrow">YOUR CATALOGUE</span><h1>Products & services</h1><p class="muted">Reuse prices and descriptions on new documents.</p></div><button v-if="auth.manager" class="button primary" @click="edit()">Add product</button></div><p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="message" class="success" role="status">{{ message }}</p><section v-if="showForm" class="panel admin-panel"><h2>{{ editId?'Edit product':'New product' }}</h2><form @submit.prevent="save"><div class="form-grid"><label>SKU<input v-model="form.sku" required maxlength="80"></label><label>Name<input v-model="form.name" required maxlength="150"></label><label>Unit<input v-model="form.unit" required maxlength="30"></label><label>Currency<CurrencyPicker v-model="form.currency"/></label><label>Price ({{ form.currency }})<input v-model="form.unit_price" type="number" min="0" :step="1/moneyFactor(form.currency)" required></label><label><input type="checkbox" v-model="form.is_active"> Active in catalogue</label></div><label>Description<textarea v-model="form.description" maxlength="2000"/></label><div class="admin-filter"><button class="button primary" :disabled="busy">Save product</button><button type="button" class="button secondary" @click="showForm=false">Cancel</button></div></form></section>
<section class="panel admin-panel spaced"><form class="admin-filter" @submit.prevent="run(()=>load())"><label>Find products<input v-model="search" maxlength="100"></label><button class="button secondary" :disabled="busy">Search</button></form><div class="table-scroll"><table><thead><tr><th>SKU</th><th>Product</th><th>Unit</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="p in products?.data" :key="p.id"><td>{{ p.sku }}</td><td>{{ p.name }}</td><td>{{ p.unit }}</td><td>{{ formatMoney(p.unit_price_minor,p.currency) }}</td><td>{{ p.is_active?'Active':'Inactive' }}</td><td><button v-if="auth.manager" class="button secondary" @click="edit(p)">Edit</button></td></tr><tr v-if="!products?.data.length"><td colspan="6">No products yet. Add one or import your catalogue.</td></tr></tbody></table></div><div v-if="products" class="admin-pagination"><button class="button secondary" :disabled="busy||products.current_page===1" @click="run(()=>load(products!.current_page-1))">Previous</button><span>{{ products.total }} products · Page {{ products.current_page }}</span><button class="button secondary" :disabled="busy||products.current_page===products.last_page" @click="run(()=>load(products!.current_page+1))">Next</button></div></section>
<section v-if="auth.manager" class="panel admin-panel spaced"><h2>Import catalogue</h2><p class="muted">UTF-8 CSV or Excel XLSX, up to 2 MB and 500 product rows. Use the first sheet and exact template headers. Replace formulas with values; legacy XLS is unsupported.</p><div class="admin-filter"><button class="button secondary" :disabled="busy" @click="template('csv')">Download CSV template</button><button class="button secondary" :disabled="busy" @click="template('xlsx')">Download Excel template</button></div><label>Import file<input type="file" accept=".csv,.xlsx" :disabled="busy" @change="selectFile"></label><label><input type="checkbox" v-model="updateExisting" @change="preview=null"> Update existing SKUs (replaces catalogue fields only)</label><button class="button secondary spaced" :disabled="busy||!file" @click="importFile()">Preview import</button><div v-if="preview"><p>{{ preview.create_count }} new products · {{ preview.update_count }} updates</p><p v-for="e in preview.errors" :key="e.row+e.message" class="error">Row {{ e.row }}: {{ e.message }}</p><div class="table-scroll"><table><thead><tr><th>SKU</th><th>Name</th><th>Currency</th></tr></thead><tbody><tr v-for="(row,n) in preview.rows.slice(0,20)" :key="n"><td>{{ row.sku }}</td><td>{{ row.name }}</td><td>{{ row.currency }}</td></tr></tbody></table></div><small>Showing up to 20 rows. No data is saved by the preview.</small><button class="button primary spaced" :disabled="busy||!preview.can_import" @click="importFile(true)">Confirm import</button></div></section></template>
