<?php
namespace App\Http\Controllers;
use App\Models\{CommercialDocument,Invoice,Business};
use App\Services\{CurrencyService,InvoiceTotalsService,InvoiceNumberService,MediaStorage};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class CommercialDocumentController extends Controller {
 private function kind(string $kind):string {return match($kind){'quotations'=>'quotation','delivery-notes'=>'delivery_note',default=>abort(404)};}
 private function check(string $kind,CommercialDocument $document):void {abort_unless($document->kind===$this->kind($kind),404);}
 private function data(Request $r,string $kind):array {
  $rules=(new \App\Http\Requests\StoreInvoiceRequest())->setUserResolver(fn()=>$r->user())->rules();
  unset($rules['po_number']);$rules['currency']=['required',Rule::in(app(CurrencyService::class)->codes())];$rules['delivery_address']='nullable|string|max:2000';
  $data=$r->validate($rules);$data['currency_minor_units']=app(CurrencyService::class)->precision($data['currency']);
  if($kind==='delivery_note'){$data['discount_kobo']=0;$data['tax_percent']=0;foreach($data['items'] as &$item)$item['unit_price_kobo']=0;unset($item);}
  $result=app(InvoiceTotalsService::class)->calculate($data['items'],$data['discount_kobo']??0,$data['tax_percent']);$items=$result['items'];unset($result['items'],$data['items']);return [array_merge($data,$result),$items];
 }
 private function number(int $id,string $kind):string {
  $column=$kind==='quotation'?'next_quotation_number':'next_delivery_number';
  if(DB::getDriverName()==='sqlite')Business::whereKey($id)->update([$column=>DB::raw($column)]);
  $b=Business::whereKey($id)->lockForUpdate()->firstOrFail();do{if($b->$column>2147483646)throw \Illuminate\Validation\ValidationException::withMessages(['number'=>'Document counter limit reached.']);$number=($kind==='quotation'?$b->quotation_prefix.$b->quotation_separator:'DN-').str_pad((string)$b->$column,$kind==='quotation'?$b->quotation_padding:4,'0',STR_PAD_LEFT);$b->increment($column);}while(CommercialDocument::withoutGlobalScopes()->where('business_id',$id)->where('kind',$kind)->where('number',$number)->exists());return $number;
 }
 public function index(Request $r,string $kind){$q=CommercialDocument::with('client')->where('kind',$this->kind($kind));$r->validate(['search'=>'nullable|string|max:100','status'=>'nullable|string|max:20']);if($r->filled('search'))$q->where('number','like','%'.$r->search.'%');if($r->filled('status'))$q->where('status',$r->status);return $q->latest('id')->paginate(20);}
 public function show(string $kind,CommercialDocument $document){$this->check($kind,$document);return $document->load(['client','business','items']);}
 public function store(Request $r,string $kind){$type=$this->kind($kind);[$data,$items]=$this->data($r,$type);return DB::transaction(function()use($r,$type,$data,$items){$d=CommercialDocument::create($data+['business_id'=>$r->user()->business_id,'created_by'=>$r->user()->id,'kind'=>$type,'number'=>$this->number($r->user()->business_id,$type),'status'=>'draft']);$d->items()->createMany($items);return response()->json($d->load(['client','items']),201);},5);}
 public function update(Request $r,string $kind,CommercialDocument $document){$this->check($kind,$document);[$data,$items]=$this->data($r,$document->kind);return DB::transaction(function()use($document,$data,$items){$d=CommercialDocument::whereKey($document->id)->lockForUpdate()->firstOrFail();abort_unless($d->status==='draft',422,'Only draft documents can be edited.');$d->update($data);$d->items()->delete();$d->items()->createMany($items);return $d->load(['client','items']);},5);}
 public function transition(Request $r,string $kind,CommercialDocument $document){$this->check($kind,$document);$data=$r->validate(['action'=>'required|in:issue,accept,decline,deliver','received_by'=>'nullable|string|max:150']);return DB::transaction(function()use($r,$document,$data){$d=CommercialDocument::whereKey($document->id)->lockForUpdate()->firstOrFail();$next=match($data['action']){'issue'=>$d->status==='draft'?'issued':null,'accept'=>$d->kind==='quotation'&&$d->status==='issued'?'accepted':null,'decline'=>$d->kind==='quotation'&&$d->status==='issued'?'declined':null,'deliver'=>$d->kind==='delivery_note'&&$d->status==='issued'?'delivered':null};abort_unless($next,422,'This transition is not available.');if($data['action']!=='issue')abort_unless($r->user()->isManager(),403);if($next==='accepted')abort_if($d->due_date->lt(today()),422,'This quotation has expired.');$patch=['status'=>$next];if($next==='delivered'){abort_unless(!empty($data['received_by']),422,'Enter the person who received the delivery.');$patch+=['received_by'=>$data['received_by'],'delivered_at'=>now()];}$d->update($patch);return $d->load(['client','items']);},5);}
 public function convert(Request $r,string $kind,CommercialDocument $document,InvoiceNumberService $numbers){$this->check($kind,$document);abort_unless($r->user()->isManager(),403);return DB::transaction(function()use($r,$document,$numbers){$d=CommercialDocument::whereKey($document->id)->lockForUpdate()->firstOrFail();abort_unless($d->kind==='quotation',422);if($d->invoice_id)return Invoice::findOrFail($d->invoice_id)->load(['client','items','business']);abort_unless($d->status==='accepted',422,'Accept the quotation before converting.');$data=$d->only(['client_id','currency','currency_minor_units','subtotal_kobo','discount_kobo','tax_percent','tax_kobo','total_kobo','notes','terms']);$invoice=Invoice::create($data+['business_id'=>$d->business_id,'created_by'=>$r->user()->id,'number'=>$numbers->next($d->business_id),'status'=>'draft','public_token'=>(string)\Illuminate\Support\Str::uuid(),'issue_date'=>today(),'due_date'=>today()->addDays(14)]);$invoice->items()->createMany($d->items->map(fn($x)=>$x->only(['description','unit','quantity','unit_price_kobo','line_total_kobo','position']))->all());$d->update(['invoice_id'=>$invoice->id,'status'=>'converted']);return response()->json($invoice->load(['client','items','business']),201);},5);}
 public function fromInvoice(Request $r,Invoice $invoice){return DB::transaction(function()use($r,$invoice){$i=Invoice::whereKey($invoice->id)->lockForUpdate()->firstOrFail();abort_if(in_array($i->status,['draft','void']),422,'Use an issued invoice for a delivery note.');$d=CommercialDocument::create(['business_id'=>$i->business_id,'client_id'=>$i->client_id,'created_by'=>$r->user()->id,'invoice_id'=>$i->id,'kind'=>'delivery_note','number'=>$this->number($i->business_id,'delivery_note'),'status'=>'draft','currency'=>$i->currency,'currency_minor_units'=>$i->currency_minor_units,'issue_date'=>today(),'due_date'=>today(),'delivery_address'=>$i->client->address]);$d->items()->createMany($i->items->map(fn($x)=>['description'=>$x->description,'unit'=>$x->unit,'quantity'=>$x->quantity,'unit_price_kobo'=>0,'line_total_kobo'=>0,'position'=>$x->position])->all());return response()->json($d->load(['client','items']),201);},5);}
 public function pdf(string $kind,CommercialDocument $document,MediaStorage $media){$this->check($kind,$document);$document->load(['business','client','items']);$logo=$media->dataUri($document->business->logoAsset());return \Barryvdh\DomPDF\Facade\Pdf::loadView('pdf.commercial-document',['d'=>$document,'logo'=>$logo])->setPaper('a4')->setOption('isRemoteEnabled',false)->download($document->number.'.pdf');}
}
