import { test,expect } from '@playwright/test'
test('compiled frontend and real production API work under /backend',async({page,request,baseURL})=>{
 const email=`ci-${Date.now()}@example.test`
 await page.goto('/register')
 await page.getByLabel('Business name').fill('CI Production Mirror')
 await page.getByLabel('Your name',{exact:true}).fill('CI Owner')
 await page.getByLabel('Email address').fill(email)
 await page.getByLabel('Password',{exact:true}).fill('ci-test-password-123')
 await page.getByLabel('Confirm password').fill('ci-test-password-123')
 await page.getByRole('button',{name:'Create workspace'}).click()
 await expect(page.getByRole('link',{name:'Overview',exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:'Platform admin'})).toHaveCount(0)
 const token=await page.evaluate(()=>localStorage.getItem('invoice_token'))
 const headers={Authorization:`Bearer ${token}`}
 for(const path of ['/backend/api/platform/users','/backend/api/platform/integrations','/backend/api/platform/activity','/backend/api/platform/overview','/backend/api/platform/payment-emails'])expect((await request.get(path,{headers})).status()).toBe(403)
 expect((await request.put('/backend/api/platform/settings',{headers,data:{product_name:'Attacker'}})).status()).toBe(403)
 const clientRes=await request.post('/backend/api/clients',{headers,data:{name:'Test Client',email:'client@example.test',phone:'+2348031234567'}})
 expect(clientRes.status()).toBe(201);const client=await clientRes.json()
 const invoiceRes=await request.post('/backend/api/invoices',{headers,data:{client_id:client.id,issue_date:'2026-10-02',due_date:'2026-10-16',tax_percent:7.5,discount_kobo:0,items:[{description:'CI service',quantity:1,unit_price_kobo:100000}]}})
 expect(invoiceRes.status()).toBe(201);const invoice=await invoiceRes.json();expect(invoice.total_kobo).toBe(107500)
 const pdf=await request.get(`/backend/api/invoices/${invoice.id}/pdf`,{headers});expect(pdf.status()).toBe(200);expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-')
 const csv=await request.get('/backend/api/products/template/csv',{headers});expect(csv.status()).toBe(200)
 const preview=await request.post('/backend/api/products/import',{headers,multipart:{preview:'1',file:{name:'products.csv',mimeType:'text/csv',buffer:await csv.body()}}});expect(preview.status()).toBe(200);expect((await preview.json()).can_import).toBe(true)
 const xlsx=await request.get('/backend/api/products/template/xlsx',{headers});expect(xlsx.status()).toBe(200)
 const quoteRes=await request.post('/backend/api/documents/quotations',{headers,data:{client_id:client.id,currency:'JPY',issue_date:'2026-10-02',due_date:'2099-01-01',tax_percent:0,items:[{description:'Mirror quotation',unit:'pcs',quantity:2,unit_price_kobo:100}]}});expect(quoteRes.status()).toBe(201);const quote=await quoteRes.json();expect(quote.total_kobo).toBe(200)
 const quoteUrl=`/backend/api/documents/quotations/${quote.id}`
 for(const action of ['issue','accept'])expect((await request.post(quoteUrl+'/transition',{headers,data:{action}})).status()).toBe(200)
 const converted=await request.post(quoteUrl+'/convert',{headers});expect(converted.status()).toBe(201);const convertedInvoice=await converted.json()
 expect((await (await request.post(quoteUrl+'/convert',{headers})).json()).id).toBe(convertedInvoice.id)
 const quotePdf=await request.get(quoteUrl+'/pdf',{headers});expect((await quotePdf.body()).subarray(0,5).toString()).toBe('%PDF-')
 const delivery=await request.post('/backend/api/documents/delivery-notes',{headers,data:{client_id:client.id,currency:'USD',issue_date:'2026-10-02',due_date:'2026-10-16',tax_percent:0,items:[{description:'Mirror delivery',unit:'pcs',quantity:1,unit_price_kobo:999}]}});expect(delivery.status()).toBe(201);expect((await delivery.json()).total_kobo).toBe(0)
 await page.goto('/quotations');await expect(page.getByText(quote.number,{exact:true})).toBeVisible()
 await page.getByRole('link',{name:'Delivery notes',exact:true}).click();await expect(page.getByRole('heading',{name:'Delivery notes',exact:true})).toBeVisible()
 await page.getByRole('link',{name:'Products',exact:true}).click();await expect(page.getByRole('heading',{name:'Products & services'})).toBeVisible()
 await page.goto('/invoices');await page.reload();await expect(page.getByText(invoice.number,{exact:true})).toBeVisible()
 for(const path of ['/backend/.env','/backend/composer.json','/backend/vendor/autoload.php'])expect((await request.get(path)).status()).toBe(404)
 await page.goto('/about');await expect(page.getByRole('heading',{name:/free invoicing/})).toBeVisible();expect(await page.locator('script[data-invoice-ads]').count()).toBe(0)
 expect((await request.get('/backend/ads.txt')).headers()['content-type']).toContain('text/plain')
 expect((await request.get('/backend/up')).status()).toBe(200)
 expect((await request.get('/release.json')).status()).toBe(200)
})
